### ISSUE TITLE
missing class A and B?

### ISSUE THREAD

**Issue by aaronpdennis** [bcj/lcc#1]
Great package, super useful, thank you. 

Any reason the `lcco_a.doc`, `lcco_b.doc`, and their corresponding `.txt` files are missing from the provided default files? Easy enough to add, just wondering if their was something about those specific classes.

**Comment by bcj** [comment]
Definitely a mistake on my part, thanks for pointing this out. I'm pretty bad at project maintenance, but I'll try to fix this today or tomorrow.

**Comment by aaronpdennis** [comment]
@bcj pull request #2

**Comment by bcj** [comment]
Thanks!
